#!/bin/bash

echo
echo '******************************'
echo ' pdf.js - cloud tests'
echo '******************************'
echo

# All pushes go into ~/pushed. Make sure dir exists
mkdir ~/pushed 2>/dev/null

COMMIT=$(sed 's/\([a-f0-9]*\) \([a-f0-9]*\).*/\2/' < /dev/stdin)

echo
echo '*** [post-receive] creating directory for commit'
echo
cd ~/pushed; rm -rf $COMMIT 2>/dev/null; git clone ~/pdf.js $COMMIT

echo
echo '*** [post-receive] running tests'
echo
cd ~/pushed/$COMMIT
make test

echo
echo '*** [post-receive] all done.'
echo

