#!/bin/bash
# Deploy script for pdf.js cloud test runs

if [ ! $1 ];
then
  echo 'usage: deploy <target_dir>'
  echo
  exit
fi


echo '[deploy] Copying test-specific files to target pdf.js repo...'
cp -Rf test/* $1/test
echo


